apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy
  labels:
    app: autodeploy
  namespace: namespace-workflow-1715840573086
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy
  template:
    metadata:
      labels:
        app: autodeploy
    spec:
      containers:
        - name: autodeploy
          image: acrworkflow1715840573086.azurecr.io/image-workflow-1715840573086:latest
          ports:
            - containerPort: 5000